name: docker-publish
on:
  release:
    types: [published]
env:
  BUILD_TAG: ci
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          make pull
          make test-all

  push_to_registry:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build latest image
        run: |
          make pull
          TAG=$BUILD_TAG make build

      - name: Build latest base image
        run: TAG=$BUILD_TAG make build-base

      - name: Build tf12 image
        run: TAG=$BUILD_TAG make build-tf12

      - name: Build tf12 base image
        run: TAG=$BUILD_TAG make build-tf12-base

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push images to GitHub Container Registry
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          echo VERSION=$VERSION

          make publish-tf12-base
          make publish-tf12
          make publish-base
          make publish
